## NumPy for Artificial Intelligence

# TASK:1

In [1]:
import numpy as np

In [3]:
#1D array from 1 to 10
arr1 = np.arange(1, 11)
#2D array of size 3×3
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
#array of zeros (4×4)
zeros_arr = np.zeros((4,4))
#array of ones (2×5)
ones_arr = np.ones((2,5))
print("1D Array:\n", arr1)
print("2D Array:\n", arr2)
print("Zeros Array:\n", zeros_arr)
print("Ones Array:\n", ones_arr)

1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# TASK:2

In [5]:
array2D = np.array([[5,10,15],[20,25,30]])
print("Shape:", array2D.shape)
print("Size:", array2D.size)
print("Data type:", array2D.dtype)
print("Dimensions:", array2D.ndim)

Shape: (2, 3)
Size: 6
Data type: int64
Dimensions: 2


In [6]:
#Why shape is important in AI?
#Because AI models use matrices/vectors, and correct shape is required for:
#Feeding data to neural networks
#Matrix multiplication
#Feature alignment
#If shape is wrong it will break the models

# TASK:3

In [8]:
arr = np.array([10,20,30,40,50,60])
print("1st element:", arr[0])
print("Last element:", arr[-1])
print("3rd element:", arr[2])
print("Values > 30:", arr[arr > 30])

1st element: 10
Last element: 60
3rd element: 30
Values > 30: [40 50 60]


# TASK:4


In [11]:
arr = np.array([10,20,30,40,50,60])
# index 1 to 4
print(arr[1:5])
# reverse
print(arr[::-1])
# alternate
print(arr[::2])  


[20 30 40 50]
[60 50 40 30 20 10]
[10 30 50]


In [12]:
#3×3 Matrix slicing
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m[0])         
print(m[:,1])        
print(m[1:])        

[1 2 3]
[2 5 8]
[[4 5 6]
 [7 8 9]]


# TASK:5

In [14]:
v = np.array([1,2,3,4,5])
print("multiply by 5:", v * 5)
print("add 10:", v + 10)
print("square:", v ** 2)

multiply by 5: [ 5 10 15 20 25]
add 10: [11 12 13 14 15]
square: [ 1  4  9 16 25]


In [15]:
#Why Vectorization Matters?
#Instead of slow loops, NumPy performs operations at C speed.
#AI needs millions of calculations, vectorization makes it fast.

# TASK:6

In [16]:
b = np.array([[1,2,3],[4,5,6]])
print(b + 10) #add 10 everywhere
print(b * 2) #multiply array

[[11 12 13]
 [14 15 16]]
[[ 2  4  6]
 [ 8 10 12]]


In [17]:
#How broadcasting helps in ML?
#Broadcasting lets AI apply operations like:
#>scaling
#>normalization
#>bias addition
#without loops, making ML computations fast.

# TASK:7

In [18]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
print(m1 + m2) #addition
print(m1 - m2) #subtraction

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


# TASK:8

In [20]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B)) # matrix multiplication
print(A.T) # transpose

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [21]:
#Relation to Neural Networks:
#Neural Networks perform weights × inputs which is matrix multiplication.

# TASK:9

In [26]:
rand_int = np.random.randint(1, 100, (4,4))
rand_float = np.random.random((3,3))
print("Random Integers:\n", rand_int)
print("Random Decimals:\n", rand_float)
print("Max:", rand_int.max())
print("Min:", rand_int.min())
print("Average:", rand_int.mean())

Random Integers:
 [[40  3 48 82]
 [43 41  8 89]
 [89  6 34  5]
 [98 26 76 58]]
Random Decimals:
 [[0.77145303 0.30713638 0.29951179]
 [0.04887741 0.207638   0.15787129]
 [0.6346523  0.7985558  0.94674398]]
Max: 98
Min: 3
Average: 46.625


In [27]:
#Why random numbers in AI?
#Used for:
#Initializing neural network weights
#Generating training samples
#Random shuffling for stochastic gradient descent (SGD)

# TASK:10

In [28]:
marks = np.array([45,67,89,90,34,76,88,59,99,48])
print("Average:", marks.mean())
print("Highest:", marks.max())
print("Lowest:", marks.min())
print("Students above 80:", marks[marks > 80])
print("Failed students (<50):", marks[marks < 50])

Average: 69.5
Highest: 99
Lowest: 34
Students above 80: [89 90 88 99]
Failed students (<50): [45 34 48]


# TASK:11

In [29]:
import numpy as np
image = np.random.randint(0, 256, (5,5))
print("Image Pixel Matrix:\n", image)
print("Brightest Pixel:", image.max())
print("Darkest Pixel:", image.min())
print("Shape of Image:", image.shape)

Image Pixel Matrix:
 [[250 244  83 216 184]
 [ 97 109  62 181  99]
 [180 219 239 241  39]
 [ 45 118 248  47 140]
 [219  19 145  57 179]]
Brightest Pixel: 250
Darkest Pixel: 19
Shape of Image: (5, 5)


In [30]:
#How AI reads images?
#AI treats images as arrays (matrices):
#Grayscale image,2D array
#RGB image,3D array (Height × Width × 3)
#Neural networks perform matrix operations to detect edges, patterns, objects.

# TASK:12

In [31]:
import numpy as np
data = np.array([10, 25, 45, 60, 90])
print("Original Data:", data)
x_min = data.min()
x_max = data.max()
normalized_data = (data - x_min) / (x_max - x_min)
print("Normalized Data:", normalized_data)

Original Data: [10 25 45 60 90]
Normalized Data: [0.     0.1875 0.4375 0.625  1.    ]


In [32]:
#Why normalization improves AI performance?
#Normalization:
#Keeps all features on same scale (0–1)
#Speeds up training
#Prevents large-valued features from dominating
#Helps gradient descent converge faster
#Improves stability of neural networks
#Thus, normalization helps ML and AI models learn more efficiently.

# TASK:13

In [33]:
dataset = np.array([
    [22, 20000, 0],
    [25, 35000, 1],
    [30, 50000, 1],
    [35, 62000, 0],
    [40, 80000, 1],
    [50, 90000, 1]
])
print("Dataset:\n", dataset)

Dataset:
 [[   22 20000     0]
 [   25 35000     1]
 [   30 50000     1]
 [   35 62000     0]
 [   40 80000     1]
 [   50 90000     1]]


In [34]:
X = dataset[:, :2]
y = dataset[:, 2] 
print("Input Features (X):\n", X)
print("Output Labels (y):", y)

Input Features (X):
 [[   22 20000]
 [   25 35000]
 [   30 50000]
 [   35 62000]
 [   40 80000]
 [   50 90000]]
Output Labels (y): [0 1 1 0 1 1]


In [35]:
average_salary = dataset[:,1].mean()
print("Average Salary:", average_salary)

Average Salary: 56166.666666666664


In [36]:
highest_age = dataset[:,0].max()
print("Highest Age:", highest_age)

Highest Age: 50


In [37]:
print("Dataset Shape:", dataset.shape)

Dataset Shape: (6, 3)
