# MINI PROJECT

# Create Dataset of 10 Students Using NumPy

In [8]:
import numpy as np
students_data = np.array([
    [78, 85, 80, 90, 1],
    [45, 50, 40, 48, 0],
    [88, 92, 84, 95, 1],
    [60, 58, 65, 70, 1],
    [35, 40, 38, 45, 0],
    [90, 91, 89, 94, 1],
    [55, 60, 52, 58, 1],
    [30, 25, 40, 35, 0],
    [72, 75, 70, 80, 1],
    [48, 45, 50, 47, 0]
])
print("Students Dataset:\n")
# Proper column headings
print("{:<10} {:<10} {:<10} {:<10} {:<10}".format(
    "Math", "Science", "English", "Computer", "Result"))
# Print rows properly aligned
for row in students_data:
    print("{:<10} {:<10} {:<10} {:<10} {:<10}".format(
        row[0], row[1], row[2], row[3], row[4]))
print("\nResult:")
print("1 = Pass")
print("0 = Fail")

Students Dataset:

Math       Science    English    Computer   Result    
78         85         80         90         1         
45         50         40         48         0         
88         92         84         95         1         
60         58         65         70         1         
35         40         38         45         0         
90         91         89         94         1         
55         60         52         58         1         
30         25         40         35         0         
72         75         70         80         1         
48         45         50         47         0         

Result:
1 = Pass
0 = Fail


# Separate Features (X) and Labels (y)

In [13]:
# Features (marks only)
X = students_data[:, :-1]
# Labels (Result column)
y = students_data[:, -1]
print("Features (X):")
print(X)
print("\nLabels (y):")
print(y)

Features (X):
[[78 85 80 90]
 [45 50 40 48]
 [88 92 84 95]
 [60 58 65 70]
 [35 40 38 45]
 [90 91 89 94]
 [55 60 52 58]
 [30 25 40 35]
 [72 75 70 80]
 [48 45 50 47]]

Labels (y):
[1 0 1 1 0 1 1 0 1 0]


# Calculate Average, Maximum, and Minimum Marks

In [23]:
average = np.mean(marks)
maximum = np.max(marks)
minimum = np.min(marks)
print("Average Marks:", average)
print("Maximum Marks:", maximum)
print("Minimum Marks:", minimum)

Average Marks: 65.375
Maximum Marks: 90
Minimum Marks: 40


# Find Number of Students Who Passed and Failed

In [18]:
# Count passed students
passed_students = np.sum(y == 1)
# Count failed students
failed_students = np.sum(y == 0)
print("\nNumber of Passed Students =", passed_students)
print("Number of Failed Students =", failed_students)


Number of Passed Students = 6
Number of Failed Students = 4


# Identify Students Scoring Above 80 and Below 50

In [20]:
# Students scoring above 80 in any subject
above_80 = X[X > 80]
# Students scoring below 50 in any subject
below_50 = X[X < 50]
print("Marks Above 80:")
print(above_80)
print("\nMarks Below 50:")
print(below_50)

Marks Above 80:
[85 90 88 92 84 95 90 91 89 94]

Marks Below 50:
[45 40 48 35 40 38 45 30 25 40 35 48 45 47]


# Normalize the Dataset

In [26]:
# Apply normalization on marks only
min_values = np.min(X, axis=0)
max_values = np.max(X, axis=0)
x_norm = (X - min_values) / (max_values - min_values)
print("Normalized Dataset:")
print(x_norm)

Normalized Dataset:
[[0.8        0.89552239 0.82352941 0.91666667]
 [0.25       0.37313433 0.03921569 0.21666667]
 [0.96666667 1.         0.90196078 1.        ]
 [0.5        0.49253731 0.52941176 0.58333333]
 [0.08333333 0.2238806  0.         0.16666667]
 [1.         0.98507463 1.         0.98333333]
 [0.41666667 0.52238806 0.2745098  0.38333333]
 [0.         0.         0.03921569 0.        ]
 [0.7        0.74626866 0.62745098 0.75      ]
 [0.3        0.29850746 0.23529412 0.2       ]]


# Apply Simple Prediction Logic

In [27]:
# Simple prediction logic
# If average marks >= 50 → Pass
# Otherwise → Fail
average_student_marks = np.mean(X, axis=1)
predictions = np.where(average_student_marks >= 50, 1, 0)
print("\nPredicted Results:\n")
print(predictions)


Predicted Results:

[1 0 1 1 0 1 1 0 1 0]


# Calculate Accuracy of Predictions

In [28]:
# Calculate prediction accuracy
correct_predictions = np.sum(predictions == y)
accuracy = (correct_predictions / len(y)) * 100
print("\nCorrect Predictions =", correct_predictions)
print("Accuracy =", accuracy, "%")


Correct Predictions = 10
Accuracy = 100.0 %
